import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
		// Gets the two command-line arguments
		int T = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
		// Initailizes a random numbers generator with the given seed value
        Random generator = new Random(seed);  
		
		//// In the previous version of this program, you used a statement like:
		//// double rnd = Math.random();
		//// Where "rnd" is the variable that stores the generated random value.
		//// In this version of the program, replace this statement with:
		//// double rnd = generator.nextDouble();
		//// This statement will generate a random value in the range [0,1),
		//// just like you had in the previous version, except that the 
		//// randomization will be based on the given seed.
		//// This is the only change that you have to do in the program.

        int familiesWithTwoChildren = 0;
        int familiesWithThreeChildren = 0;
        int familiesWithFourOrMoreChildren = 0;
        String mostCommon;
        Double totalChildCount = 0.0;

        for (int i = 0; i < T; ++i) {
            Boolean boyCreated = false;
            Boolean girlCreated = false;
            int childrenCount = 0;

            while (!boyCreated || !girlCreated) {
                if (generator.nextDouble() <= 0.5) {
                    boyCreated = true;
                } else {
                    girlCreated = true;
                }
                childrenCount++;
            }

            totalChildCount += childrenCount;

            if (childrenCount >= 4) {
                familiesWithFourOrMoreChildren++;
            } else if (childrenCount == 3) {
                familiesWithThreeChildren++;
            } else {
                familiesWithTwoChildren++;
            }
        }

        System.out.printf("Average: %f children to get at least one of each gender.\n", totalChildCount / T );
        System.out.printf("Number of families with 2 children: %d\n", familiesWithTwoChildren);
        System.out.printf("Number of families with 3 children: %d\n", familiesWithThreeChildren);
        System.out.printf("Number of families with 4 or more children: %d\n", familiesWithFourOrMoreChildren);

        if (familiesWithFourOrMoreChildren > familiesWithThreeChildren) {
            mostCommon = familiesWithFourOrMoreChildren > familiesWithTwoChildren ? "4 or more" : "2";
        } else {
            mostCommon = familiesWithThreeChildren > familiesWithTwoChildren ? "3" : "2";
        }
        System.out.printf("The most common number of children is %s.\n", mostCommon);
	}
}
